workflows:
  install:
    jobs:
      - yarn
      - lint:
          requires:
            - yarn
  tests:
    jobs:
      - bdd
jobs:
  yarn:
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  lint:
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test:ci
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  bdd:
    docker:
      - image: 'circleci/node:12'
        environment:
          DATABASE_URL: postgres://psqluser:psqlpassword@localhost:5432/psdb
          JWT_SECRET: bla bla
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
      - image: 'circleci/postgres:9.6.2-alpine'
        environment:
          POSTGRES_USER: psqluser
          POSTGRES_PASSWORD: psqlpassword
          POSTGRES_DB: psdb

    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test:e2e
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules